[package]
name = "mesh-loader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.14"
test-log = "0.2.13"
ply-rs = "0.1.3"
math = {path = "../math"}

[dev-dependencies]
env_logger = "*"
tracing-subscriber = {version = "0.3", default-features = false, features = ["env-filter", "fmt"]}